### ISSUE TITLE
Problem starting serialmidi.py on mac os

### ISSUE THREAD

**Issue by meirinaldojunior** [raspy135/serialmidi#2] opened 2020-09-25 09:34 UTC
Hi,

i'm trying run `python serialmidi.py --serial_name=/dev/cu.usbmodem1444201 --midi_in_name="IAC Bus 1" --midi_out_name="IAC Bus 2" `

But, i'm receiving erro: 
`MIDI IN Device name is incorrect. Please use listed device name.`
`MIDI OUT Device name is incorrect. Please use listed device name.`

**Comment by raspy135** [comment] 2020-09-25 19:34
Could you run it without MIDI device name and copy the output here?
serialmidi.py --serial_name=[serial_port] --baud=[baud]
It will show the list of MIDI devices

**Comment by raspy135** [comment] 2020-10-01 03:57
I assume the issue is solved? I will close this, please reopen it if you still have issues.

**Closed as completed by raspy135** 2020-10-01 03:57 UTC

**Comment by Grumpy-Mike** [comment] 2023-12-22 05:17
I am having the same problem. When I run:-
`python3 serialmidi.py --serial_name=["/dev/cu.usbmodem14201"] --baud=[115200]`

with or without quotes on the device name then I get:-

`//usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python: can't open file 'serialmidi.py': [Errno 2] No such file or directory
`

`/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python: can't open file 'serialmidi.py': [Errno 2] No such file or directory
`

I have tried putting serialmidi.py in this location to no avail.

Sorry but I have not had much experience with Python on the Mac, but I have worked a lot with it on the Raspberry Pi.
I am running this on Moajve if this matters, although I am having similar difficulties running your code on my iMac running OS Sonoma 14.2 .
